=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO8/EJERCICIO8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
<xs:element name="prestamos" type="tipoprestamos"/>

<xs:complexType name="tipoprestamos">
<xs:sequence>
      <xs:element name="prestamo" minOccurs="1" maxOccurs="unbounded" type="tipoprestamo"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="tipoprestamo">
    <xs:sequence>
    <xs:element name="bibliotecario" type="datos"></xs:element>
          <xs:element name="fechaprestamo" type="xs:date"/>
          <xs:element name="fechadevolucion" type="xs:date"/>
          <xs:element name="lector" type="tipolector"/>
          <xs:element name="ejemplares" minOccurs="0" maxOccurs="3" type="tipoejemplar"/>
    </xs:sequence>
  <xs:attribute name="codigo"  type="xs:ID" use="required"/>
</xs:complexType>


<xs:complexType name="datos">
    <xs:sequence>
     <xs:element name="nombre" type="xs:string"/>
          <xs:element name="apellido1" type="xs:string"/>
          <xs:element name="apellido2" type="xs:string"/>
          
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipoejemplar">
<xs:sequence>
    <xs:element name="numero_registro" type="xs:string"/>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="autor" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
    

</xs:sequence>
</xs:complexType>

<xs:complexType name="tipolector">
    <xs:sequence>
    <xs:element name="id" type="xs:IDREF"/>
     <xs:element name="nombre" type="xs:string"/>
          <xs:element name="apellido1" type="xs:string"/>
          <xs:element name="apellido2" type="xs:string"/>
          <xs:element name="telefono" type="tipotelefono"/>
          <xs:element name="direccion" type="tipodirecion"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipodirecion">
    <xs:sequence>
    <xs:element name="nombre_Calle" type="xs:string"/>
    <xs:element name="numero" type="xs:integer"/>
    <xs:element name="piso" type="xs:string"/>
    <xs:element name="letra" type="tipoletra"/>
    <xs:element name="codigo_postal" type="tipocodigo"/>
    <xs:element name="localidad" type="xs:string"/>
    <xs:element name="provincia" type="xs:string"/>
        
    </xs:sequence>

<xs:attribute name="tipocalle">
      <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="calle"/>
                 <xs:enumeration value="avenida"/>
              </xs:restriction>
            </xs:simpleType>
    </xs:attribute>
</xs:complexType>

<xs:simpleType name="tipocodigo">
            <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
</xs:simpleType>


<xs:simpleType name="tipoletra">
            <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z])*"/>
        </xs:restriction>
</xs:simpleType>


<xs:simpleType name="tipotelefono">
            <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
</xs:simpleType>

</xs:schema>

=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO8/EJERCICIO8.xml
<?xml version="1.0" encoding="UTF-8"?>
<prestamos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='EJERCICIO8.xsd' >

<prestamo codigo="GJD" >

<bibliotecario>
<nombre>Sergio</nombre>
<apellido1>Hernandez</apellido1>
<apellido2>Rodrigez</apellido2>
</bibliotecario>

<fechaprestamo>2000-12-03</fechaprestamo>
<fechadevolucion>2000-12-15</fechadevolucion>
<lector>
          <id>GJD</id>
          <nombre>carmen</nombre>
          <apellido1>Rendon</apellido1>
          <apellido2>Carrabeo</apellido2>
          <telefono>123456789</telefono>
          <direccion tipocalle="calle">
                 
                  <nombre_Calle>comercio</nombre_Calle>

                  <numero>23</numero>
                  <piso>piso1</piso>
                  <letra>A</letra>
                  <codigo_postal>4125</codigo_postal>
                  <localidad>sevilla</localidad>
                  <provincia>Mairena del aljarafe</provincia>
          </direccion>
        
</lector>
 
          <ejemplares>
              <numero_registro>123</numero_registro>    
              <titulo>el principito</titulo>      
              <autor>anonimo</autor>
          </ejemplares>
</prestamo>

<prestamo codigo="DLP">

<bibliotecario>
<nombre>Laura</nombre>

<apellido1>Ramirez</apellido1>
<apellido2>Blanco</apellido2>
</bibliotecario>

<fechaprestamo>2019-07-25</fechaprestamo>
<fechadevolucion>2019-08-06</fechadevolucion>
<lector>
          <id>DLP</id>
          <nombre>Sara</nombre>
          <apellido1>Herrera</apellido1>
          <apellido2>Carrabeo</apellido2>
          <telefono>856381734</telefono>
          <direccion tipocalle="avenida">
                  <nombre_Calle>avenida de la paz</nombre_Calle>
                  <numero>02</numero>
                  <piso>piso2</piso>
                  <letra>B</letra>
                  <codigo_postal>4562</codigo_postal>
                  <localidad>Cadiz</localidad>
                  <provincia>San Lucar de Barrameda</provincia>
          </direccion>
        
</lector>
 
          <ejemplares>
              <numero_registro>572</numero_registro>    
              <titulo>Historia de españa</titulo>      
              <autor>anonimo</autor>
          </ejemplares>

</prestamo>

</prestamos>
