=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO4/EJERCICIO4.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>


<xs:element name="universidad" type="tipouniversidad"/>

     
      <xs:complexType name="tipouniversidad">
        <xs:sequence>
           <xs:element name="profesor" minOccurs="1" maxOccurs="unbounded" type="tipoprofesor"  />
            <xs:element name="alumno" minOccurs="1" maxOccurs="unbounded" type="tipoalumno"/>
              <xs:element name="materia" minOccurs="1" maxOccurs="unbounded" type="tipomaterias"/>
        </xs:sequence>
      </xs:complexType>



<xs:complexType name="tipoprofesor">
<xs:sequence>
<xs:group  ref="tipodatos"/>
<xs:element name="despacho" type="xs:string"/>
<xs:element name="horario" type="xs:time"/>
<xs:element name="asignaturas" type="newasignatura"/>
</xs:sequence>
</xs:complexType>



<xs:complexType name="tipoalumno">
      <xs:sequence>
      <xs:group ref="tipodatos"/>
          <xs:element name="asignaturas" type="newasignatura"/>  
      </xs:sequence>

</xs:complexType>


<xs:group name="tipodatos">
<xs:sequence>
<xs:choice>
<xs:element name="dni" type="midni"/>
<xs:element name="pasaporte" type="tipopasaporte"/>
</xs:choice>
<xs:element name="nombre" type="xs:string"/>
<xs:element name="apellido1" type="xs:string"/>
<xs:element name="apellido2" type="xs:string"/>
<xs:element name="fechanacimiento" type="xs:date"/>
  <xs:choice minOccurs="0" maxOccurs="unbounded">
       <xs:element name="direcion_postal" type="xs:string" />
        <xs:element name="telefono" type="xs:integer"/>
        <xs:element name="cuentacorreo" type="xs:integer"/>    
    </xs:choice>
</xs:sequence>
</xs:group>


      <xs:simpleType name="midni">
            <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[A-Z]{1}"/>
        </xs:restriction>
</xs:simpleType>

      <xs:complexType name="tipopasaporte">
        <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="country" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
      </xs:complexType>

<xs:complexType name="newasignatura">
  <xs:sequence>
      <xs:element name="asignatura" minOccurs="1" maxOccurs="unbounded" type="listaasignatura"/>  
  </xs:sequence>
</xs:complexType>

<xs:complexType name="listaasignatura">
   <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="codigo" type="xs:IDREF"/>
          <xs:attribute name="nota">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="NP"/>
                <xs:enumeration value="SS"/>
                <xs:enumeration value="AP"/>
                <xs:enumeration value="NT"/>
                <xs:enumeration value="SB"/>
                <xs:enumeration value="MH"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
       </xs:extension>
      </xs:simpleContent>
</xs:complexType>

  <xs:complexType name="tipomaterias">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="codigo" type="xs:ID"/>
          <xs:attribute name="nCreditos" type="xs:integer"/>
          <xs:attribute name="carrera" type="xs:string"/>
          <xs:attribute name="curso" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO4/universidadxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='EJERCICIO4.xsd'>


<profesor>
       <dni>12345678J</dni>
        <nombre>carlos</nombre>
        <apellido1>perez</apellido1>
        <apellido2>ramirez</apellido2>
        <fechanacimiento>1979-03-05</fechanacimiento>
      <despacho>despacho1</despacho>
      <horario>14:00:00</horario>
      <asignaturas>
        <asignatura codigo="ABC"></asignatura>
      <asignatura  codigo="BJD"></asignatura>
      </asignaturas>
      
      
      </profesor>
      
      
<profesor>
       <dni>71973562J</dni>
        <nombre>Sergio</nombre>
        <apellido1>Hernandez</apellido1>
        <apellido2>Carrabeo</apellido2>
        <fechanacimiento>1996-11-02</fechanacimiento>
      <despacho>despacho33</despacho>
      <horario>18:30:00</horario>
      <asignaturas>
        <asignatura codigo="LER"></asignatura>
      <asignatura  codigo="PUQ"></asignatura>
      </asignaturas>
      
      
      </profesor>
    <alumno>
        <dni>12345678P</dni>
        <nombre>manuel</nombre>
        <apellido1>garcia</apellido1>
        <apellido2>rendon</apellido2>
        <fechanacimiento>1978-03-12</fechanacimiento>
         <asignaturas>
        <asignatura codigo="LER" nota="SS"></asignatura>
      <asignatura  codigo="PZD" nota="NP"></asignatura>
      <asignatura  codigo="PUQ" nota="SB"></asignatura>
      </asignaturas>
    </alumno>
    
     <alumno>
        <pasaporte country="españa">J00324</pasaporte>
        <nombre>Laura</nombre>
        <apellido1>Bejarano</apellido1>
        <apellido2>Cobos</apellido2>
        <fechanacimiento>1999-10-23</fechanacimiento>
         <asignaturas>
        <asignatura codigo="BJD" nota="SS"></asignatura>
      <asignatura  codigo="LER" nota="NP"></asignatura>
    
      </asignaturas>
    </alumno>
    
<materia codigo="LER" nCreditos="123" carrera="matematicas" curso="primero">mates</materia>
<materia codigo="PZD" nCreditos="345" carrera="bioquimica" curso="cuarto">laboratorio</materia>
<materia codigo="PUQ" nCreditos="763" carrera="economia" curso="segundo">derecho</materia>
<materia codigo="ABC" nCreditos="703" carrera="medio_ambientales" curso="quinto">quimica</materia>
<materia codigo="BJD" nCreditos="120" carrera="nutricion" curso="segundo">dieta</materia>
</universidad>
