=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO5/EJERCICIO5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
<xs:element name="biblioteca" type="tipobiblioteca"/>


 <xs:complexType name="tipobiblioteca">
        <xs:sequence>
           <xs:element name="libro" minOccurs="1" maxOccurs ="unbounded" type="tipolibro">
                 
           </xs:element>
        </xs:sequence>
      </xs:complexType>
      
      <xs:complexType name="tipolibro">
      <xs:sequence>
      <xs:element name="titulo"  type="tipotitulo"/>
     <xs:element name="autor"  type="tipoautor"/>
     <xs:element name="editorial" minOccurs="0" maxOccurs="1" type="xs:string"/>
     <xs:element name="anio" minOccurs="0" maxOccurs="1" type="xs:string"/>
      </xs:sequence>
        <xs:attribute name="genero" >
        <xs:simpleType>
          <xs:restriction base="xs:string">
          <xs:enumeration value="actas"/>
          <xs:enumeration value="novela"/>
          <xs:enumeration value="ensayo"/>
          </xs:restriction>
      </xs:simpleType>
     </xs:attribute>    
       
      </xs:complexType>

<xs:complexType name="tipotitulo" mixed="true">
    <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="subtitulo" type="xs:string"/>     
        </xs:choice>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipoautor">
<xs:sequence>
<xs:element name="nombre" minOccurs="0" maxOccurs="1" type="xs:string"/>
<xs:element name="apellido" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
</xs:sequence>
</xs:complexType>      

     
</xs:schema>

=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO5/EJERCICIO5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DOCTYPE biblioteca SYSTEM "EJERCICIO5.dtd"-->
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='EJERCICIO5.xsd'>

    <libro genero="novela">
        <titulo>harry-potter</titulo>
        <autor>
        <nombre>jk</nombre>  

        <apellido>rouwling</apellido>
          </autor>
        <editorial>salamandra</editorial>      
        <anio>1999</anio>
      
    </libro>
    
       <libro genero="actas">
        <titulo>buscandoanemo</titulo>
        <autor>

        <nombre>lala</nombre>  
        <apellido>sss</apellido>
          </autor>
        <editorial>salamandra</editorial>      
        <anio>2004</anio>
      
    </libro>
</biblioteca>
