=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO1/cancion.dtd
<!ELEMENT cancion (titulo,compositores,productores,sello,artista)>
<!ATTLIST cancion duracion CDATA #REQUIRED>
<!ATTLIST cancion anio CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombre,apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombre, apellidos)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO1/cancion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cancion SYSTEM "cancion.dtd">
<cancion duracion="4:47" anio="2008">
  <titulo>Give it 2 me</titulo>
  <compositores>
    <compositor>
        <nombre>Pharrell</nombre>
        <apellidos>Williams</apellidos>
    </compositor>  
  </compositores>
<productores>
    <productor>
        <nombre>Pharrell</nombre>  
        <apellidos>Williams</apellidos>  
    </productor>
</productores>
<sello>Warnes Bros</sello>
<artista>Madonna</artista>
</cancion>
