=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO1/cd.dtd
<!ELEMENT cd (songs)>
<!ATTLIST cd titulo CDATA #REQUIRED>
<!ELEMENT songs (cancion*)>

<!ELEMENT cancion (fecha,titulo,compositores,productores,sello,artista)>
<!ELEMENT fecha EMPTY>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anio CDATA #REQUIRED>
<!ATTLIST cancion duracion CDATA #REQUIRED>

<!ATTLIST cancion anio CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor)>
<!ELEMENT compositor (nombre,apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT productores (productor)>
<!ELEMENT productor (nombre, apellidos)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

=== carmenrenca/lenguaje_marca/ejercicio_xml_CARMEN_RENDON/EJERCICIO1/cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "cd.dtd">
<cd titulo="titulocd">
<songs>
<cancion duracion="4:47" anio="2008">
<fecha dia="3" mes="5" anio="2008"></fecha>
  <titulo>Give it 2 me</titulo>    
  <compositores>
    <compositor>
        <nombre>Pharrell</nombre>    
        <apellidos>Williams</apellidos>
    </compositor>
  </compositores>
<productores>
    <productor>
        <nombre>Pharrell</nombre>  
        <apellidos>Williams</apellidos>  
    </productor>
</productores>
<sello>Warnes Bros</sello>
<artista>Madonna</artista>

</cancion>

</songs>



</cd>
